apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: css
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: cephfs

